# Test профиль
spring.profiles.active=test
# Порт для тестов (может быть 8080)
server.port=8080
# In-memory база для тестов
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Hibernate для тестов
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
# Настройки для тестирования
spring.main.allow-bean-definition-overriding=true
# Минимальное логирование для тестов
logging.level.com.example.pro.sky.hogwartsApi=WARN
logging.level.root=WARN
# Аватарки для тестов
avatars.dir.path=./avatars-test