# Production профиль
spring.profiles.active=prod
# Другой порт для prod
server.port=8082
# Production база (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts_prod
spring.datasource.username=student
spring.datasource.password=chocolatefrog
# Hibernate для PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.batch_size=20
# Безопасность - отключаем H2 console
spring.h2.console.enabled=false
# Менее подробное логирование в prod
logging.level.com.example.pro.sky.hogwartsApi=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.file.name=./logs/hogwarts-api-prod.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Liquibase
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.liquibase.enabled=true
# Аватарки
avatars.dir.path=./avatars-prod