spring.application.name=pro.sky.hogwartsApi
spring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Директория для хранения аватарок
avatars.dir.path=./avatars
# Настройки для загрузки файлов
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB